#!/bin/bash

echo "Cleaning up MinIO tenants and operator"
"${SNAP_COMMON}/plugins/minio" delete

echo "Remove kubectl-minio"
rm "${SNAP_COMMON}/plugins/minio"
rm "${SNAP_COMMON}/kubectl-minio"

echo "Disabled minio addon."
