#!/bin/bash

. "${SNAP}/actions/common/utils.sh"

DIR="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
ARCH="$(arch)"

CREATE_TENANT="yes"
STORAGE_CLASS="microk8s-hostpath"
CAPACITY="20Gi"
SERVERS=1
VOLUMES=1
TENANT="microk8s"
VERSION="4.4.29"
TLS="no"
PROMETHEUS="no"
REPO="https://github.com/minio/operator"

function usage {
  echo "Usage: microk8s enable minio [OPTIONS]"
  echo ""
  echo "Enable the MinIO addon."
  echo ""
  echo "   -h               Print this help message"
  echo "   -k               Do not create default tenant"
  echo "   -s STORAGECLASS  Storage class to use for the default tenant (default: ${STORAGE_CLASS})"
  echo "   -c CAPACITY      Capacity of the default tenant (default: ${CAPACITY})"
  echo "   -n SERVERS       Servers of the default tenant (default: ${SERVERS})"
  echo "   -v VOLUMES       Volumes of the default tenant (default: ${VOLUMES})"
  echo "   -t TENANTNAME    Name of the default tenant (default: ${TENANT})"
  echo "   -T               Enable TLS for the default tenant (default: disabled)"
  echo "   -p               Enable Prometheus for the default tenant (default: disabled)"
  echo "   -r REPOSITORY    Minio Operator GitHub repository (default: ${REPO})"
  echo "   -V VERSION       Minio Operator version (default: ${VERSION})"
}

while getopts ":hkTps:c:n:v:t:r:V:" arg; do
  case "${arg}" in
    k) CREATE_TENANT="no" ;;
    s) STORAGE_CLASS="${OPTARG}" ;;
    c) CAPACITY="${OPTARG}" ;;
    n) SERVERS="${OPTARG}" ;;
    v) VOLUMES="${OPTARG}" ;;
    t) TENANT="${OPTARG}" ;;
    T) TLS="yes" ;;
    p) PROMETHEUS="yes" ;;
    V) VERSION="${OPTARG}" ;;
    r) REPO="${OPTARG}" ;;
    h)
      usage
      exit 0
      ;;
    :)
      echo "Missing argument for option -${OPTARG}"
      usage
      exit 1
      ;;
    ?)
      echo "Invalid option -${OPTARG}"
      usage
      exit 1
      ;;
  esac
done

echo "Download kubectl-minio"

if [ ! -f "${SNAP_COMMON}/kubectl-minio" ]; then
  fetch_as "${REPO}/releases/download/v${VERSION}/kubectl-minio_${VERSION}_linux_${ARCH}" "${SNAP_COMMON}/kubectl-minio"
  chmod +x "${SNAP_COMMON}/kubectl-minio"
fi

if ! "${SNAP_COMMON}/kubectl-minio" version > /dev/null; then
  echo "Could not execute kubectl-minio"
  exit 1
fi

echo "Initialize minio operator"
"${SNAP_COMMON}/kubectl-minio" --kubeconfig="${SNAP_DATA}/credentials/client.config" init

if [ "x${CREATE_TENANT}" = "xyes" ]; then
  echo "Create default tenant with:"
  echo ""
  echo "  Name: ${TENANT}"
  echo "  Capacity: ${CAPACITY}"
  echo "  Servers: ${SERVERS}"
  echo "  Volumes: ${VOLUMES}"
  echo "  Storage class: ${STORAGE_CLASS}"
  echo "  TLS: ${TLS}"
  echo "  Prometheus: ${PROMETHEUS}"
  echo ""

  declare -a ARGS=(
    "${TENANT}"
    --storage-class "${STORAGE_CLASS}"
    --capacity "${CAPACITY}"
    --servers "${SERVERS}"
    --volumes "${VOLUMES}"
    --namespace "minio-operator"
  )

  if [ "x${TLS}" = "xno" ]; then
    ARGS+=("--disable-tls")
  fi

  if [ "x${PROMETHEUS}" = "xno" ]; then
    ARGS+=("--enable-prometheus=false")
  fi

  set -x
  "${SNAP_COMMON}/kubectl-minio" --kubeconfig="${SNAP_DATA}/credentials/client.config" tenant create ${ARGS[@]}
  set +x
fi

cp "${DIR}/minio" "${SNAP_COMMON}/plugins/kubectl-minio"

echo "================================"
echo "Enabled minio addon."
echo ""
echo "You can manage minio tenants using the kubectl-minio plugin."
echo ""
echo "For more details, use"
echo ""
echo "    microk8s kubectl-minio --help"
echo ""
